### ISSUE TITLE
When i apply price filter with no products it shows out of stock products

### ISSUE THREAD

**Issue by ia-gaurav** [nordcomputer/magento2-showoutofstockprice#17] opened 2021-06-05 09:35 UTC
i enabled module it works fine show price for out of stock products.

For eg Product A is out of stock with price 200, when i appy price filter of 0-100 , still those products shows

**Comment by nordcomputer** [comment] 2021-06-06 15:01
Right now, I am not able to reproduce the error in my local environment. Did you reindex your products? Is it happening in both (category view and search results)? Is it only happening with the price filter? Are there any extensions messing around with your filters?

**Comment by nordcomputer** [comment] 2021-06-22 07:56
As there seems to be no further activity on this, I close the issue. Feel free to reopen, if the problem persists and you can provide some more information.

**Closed as completed by nordcomputer** 2021-06-22 07:56 UTC
Labels: issue needs update
